# Generated by Django 5.2.6 on 2025-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('not_urgent', 'Not urgent'), ('not_important', 'Not important')], default='important', max_length=20),
        ),
    ]
